import type { AbiFunction } from 'viem';
import type { DefiChainPolicy, DefiFunctionPolicy } from '../../defi.types';
import type { DefiRegistryFragment } from '../defi-manifest.types';
const chainId = 42161;
const router = '0xc873fEcbd354f5A56E00E710B90EF4201db2448d';
const sourceRef = 'docs/defi-research/expansion55-camelot-v5.md (Camelot AMM V2; address-specific Sourcify ABI snapshot verified 2024-08-08T15:03:36Z; retrieved 2026-10-04)';
const specs = [{"name":"addLiquidity","type":"function","inputs":[{"name":"tokenA","type":"address","internalType":"address"},{"name":"tokenB","type":"address","internalType":"address"},{"name":"amountADesired","type":"uint256","internalType":"uint256"},{"name":"amountBDesired","type":"uint256","internalType":"uint256"},{"name":"amountAMin","type":"uint256","internalType":"uint256"},{"name":"amountBMin","type":"uint256","internalType":"uint256"},{"name":"to","type":"address","internalType":"address"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"amountA","type":"uint256","internalType":"uint256"},{"name":"amountB","type":"uint256","internalType":"uint256"},{"name":"liquidity","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},{"name":"removeLiquidity","type":"function","inputs":[{"name":"tokenA","type":"address","internalType":"address"},{"name":"tokenB","type":"address","internalType":"address"},{"name":"liquidity","type":"uint256","internalType":"uint256"},{"name":"amountAMin","type":"uint256","internalType":"uint256"},{"name":"amountBMin","type":"uint256","internalType":"uint256"},{"name":"to","type":"address","internalType":"address"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"amountA","type":"uint256","internalType":"uint256"},{"name":"amountB","type":"uint256","internalType":"uint256"}],"stateMutability":"nonpayable"},{"name":"swapExactTokensForTokensSupportingFeeOnTransferTokens","type":"function","inputs":[{"name":"amountIn","type":"uint256","internalType":"uint256"},{"name":"amountOutMin","type":"uint256","internalType":"uint256"},{"name":"path","type":"address[]","internalType":"address[]"},{"name":"to","type":"address","internalType":"address"},{"name":"referrer","type":"address","internalType":"address"},{"name":"deadline","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"}] as const;
const functions: DefiFunctionPolicy[] = specs.map((spec) => {
 const abi: AbiFunction = spec as unknown as AbiFunction;
 const signature = `${spec.name}(${spec.inputs.map((input) => input.type).join(',')})`;
 const operation = spec.name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`).replace(/^-/, '');
 return { capabilityId: `camelot-v2:v2:${chainId}:${router.toLowerCase()}:${operation}`, type: 'contract_call', chainId, contract: router, functionName: spec.name, signature, abi, status: 'active', provenance: { sourceRef, verifiedAt: '2026-10-04', status: 'verified' }, protocol: 'Camelot AMM V2', operation, label: `Camelot AMM V2 ${spec.name}`, warnings: ['Caller-selected assets, amounts, recipient, path/bin distributions, slippage, and deadline are not financially constrained here.', 'Approval is independent and not provided; pool/pair population, liquidity, and execution are not asserted.'] };
});
const chains: DefiChainPolicy[] = [{ chainId, status: 'active', contracts: [{ address: router, status: 'active', functions }] }];
export function buildCamelotRegistry(): DefiRegistryFragment { return { chains }; }
