/** Isolated, fixed-fixture Ethereum Anvil evidence runner. All mutations are loopback-only. */
import { spawn, ChildProcess } from 'node:child_process';
import { createServer } from 'node:net';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
import { createPublicClient, defineChain, http, keccak256, toBytes, encodeFunctionData, parseAbi } from 'viem';

export const CHAIN_ID = 31337, SOURCE_CHAIN = 1;
export const ANVIL = '/Users/dev/.foundry/bin/anvil';
export const SOURCE_URL = 'https://ethereum-rpc.publicnode.com';
export const CALIBUR = '0x000000005c84F8Fd50b21CAC312528A64437030e';
const T = { weth:'0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', usdc:'0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', usdcImpl:'0x43506849D7C04F9138D1A2050bbF3A0c054402dd', usdcImplHash:'0xcdfb7d322961af3acae7a8f7ee8b69c205b36f576cc5b077f170c7eb8ecbe3ea', usdcImplSlot:'0x7050c9e0f4ca769c69bd3a8ef740bc37934f8e2c036e5a723fd8ee048ed3f8c3', router:'0xE592427A0AEce92De3Edee1F18E0157C05861564', factory:'0x1F98431c8aD98523631AE4a59f267346ea31F984', factoryHash:'0x4d7b8525cd5d14343fa67a732fba5b24cddba11620ca88392f4ec6c52f91fd69', pool:'0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640', aave:'0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2', impl:'0x728a138A4823392C2EFA55e028d434F526fE03CF', ethFeed:'0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419', usdFeed:'0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6' } as const;
const READ = new Set(['eth_chainId','eth_blockNumber','eth_getBlockByNumber','eth_getCode','eth_getStorageAt','eth_call','eth_getLogs']);
const LOCAL = new Set([...READ,'anvil_nodeInfo','debug_traceTransaction','eth_getTransactionReceipt','eth_estimateGas','eth_gasPrice','eth_accounts','eth_sendTransaction','anvil_impersonateAccount','anvil_stopImpersonatingAccount','anvil_setBalance','anvil_setCode']);
export function assertLocalEndpoint(url:string, child:ChildProcess, port:number, alive=child.exitCode===null):void { const u=new URL(url); if(!alive||!child.pid||u.protocol!=='http:'||u.hostname!=='127.0.0.1'||Number(u.port)!==port) throw Error('local fork ownership guard rejected endpoint'); }
export function assertReadonlyMethod(method:string, source=false):void { if(source?!READ.has(method):!LOCAL.has(method)) throw Error(source?'source RPC is read-only':'local RPC method not allowed'); }
async function freePort():Promise<number>{ return new Promise((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const a=s.address();if(!a||typeof a==='string')return reject(Error('port allocation failed'));const p=a.port;s.close(()=>resolve(p));});}); }
async function rpc(url:string, method:string, params:unknown[]=[], source=false, guard?:()=>Promise<void>):Promise<any>{ assertReadonlyMethod(method,source); if(guard) await guard(); const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(7000)});const x=await r.json() as any;if(!r.ok||x.error)throw Error(`${method}: ${String(x.error?.message||r.statusText).slice(0,180)}`);return x.result; }
const erc20=parseAbi(['function balanceOf(address) view returns(uint256)','function allowance(address,address) view returns(uint256)','function approve(address,uint256) returns(bool)','function decimals() view returns(uint8)']);
const scaledBalanceAbi=parseAbi(['function scaledBalanceOf(address) view returns(uint256)']);
const executeAbi=parseAbi(['function execute(((address,uint256,bytes)[],bool))']);
const routerAbi=parseAbi(['function exactInputSingle((address,address,uint24,address,uint256,uint256,uint256,uint160)) payable returns(uint256)']);
const factoryAbi=parseAbi(['function getPool(address,address,uint24) view returns(address)']);
const poolAbi=parseAbi(['function token0() view returns(address)','function token1() view returns(address)','function fee() view returns(uint24)','function factory() view returns(address)','function liquidity() view returns(uint128)']);
const feedAbi=parseAbi(['function decimals() view returns(uint8)','function latestRoundData() view returns(uint80,int256,uint256,uint256,uint80)']);
const aaveAbi=parseAbi(['function getReserveData(address) view returns((uint256,uint128,uint128,uint128,uint128,uint128,uint40,uint16,address,address,address,address,uint128,uint128,uint128))','function getReserveNormalizedIncome(address) view returns(uint256)','function supply(address,uint256,address,uint16)','function withdraw(address,uint256,address) returns(uint256)']);
const proxySlot='0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc';

async function main():Promise<void>{ let child:ChildProcess|undefined;let url='';let port=0;let proof:any={status:'failed',proofs:[]};const aaveOnly=process.argv.includes('--aave-only');
 try{
  if(parseInt(await rpc(SOURCE_URL,'eth_chainId',[],true),16)!==SOURCE_CHAIN)throw Error('public source chain ID is not mainnet');
  const b=await rpc(SOURCE_URL,'eth_getBlockByNumber',['latest',false],true);if(!b?.hash||!b?.number)throw Error('source latest block lacks identity'); const forkBlock=parseInt(b.number,16),forkHash=String(b.hash).toLowerCase();
  port=await freePort();url=`http://127.0.0.1:${port}`;child=spawn(ANVIL,['--silent','--host','127.0.0.1','--port',String(port),'--fork-url',SOURCE_URL,'--fork-block-number',String(forkBlock),'--chain-id',String(CHAIN_ID),'--hardfork','prague'],{stdio:'ignore'});
  const localGuard=async()=>{assertLocalEndpoint(url,child!,port);if(await rpc(url,'eth_chainId')!=='0x7a69')throw Error('owned Anvil chain ID mismatch');const lb=await rpc(url,'eth_getBlockByNumber',['0x'+forkBlock.toString(16),false]);if(lb?.hash?.toLowerCase()!==forkHash)throw Error('owned Anvil fork block mismatch');};
  for(let i=0;i<80;i++){try{await localGuard();break;}catch(e){if(child.exitCode!==null)throw Error('owned Anvil child exited during startup');if(i===79)throw e;await delay(250);}}
  // Bind the result to Anvil's own fork metadata (no substring/heuristic match).
  const ni=await rpc(url,'anvil_nodeInfo',[],false,localGuard); const meta=ni?.forkConfig;
  if(!meta||Number(meta.forkBlockNumber)!==forkBlock||String(meta.forkUrl||'').replace(/\/$/,'')!==SOURCE_URL)throw Error('Anvil nodeInfo fork configuration mismatch');
  const read=(method:string,params:unknown[]=[])=>rpc(SOURCE_URL,method,params,true);
  const sourceChain=parseInt(await read('eth_chainId'),16);if(sourceChain!==SOURCE_CHAIN)throw Error('source endpoint changed chain');
  const sourceCode=async(a:string)=>read('eth_getCode',[a,'0x'+forkBlock.toString(16)]);
  const codeHashes:any={};for(const [name,a] of Object.entries(aaveOnly?{calibur:CALIBUR,weth:T.weth,aave:T.aave,aaveImpl:T.impl}:{calibur:CALIBUR,router:T.router,factory:T.factory,pool:T.pool,weth:T.weth,usdc:T.usdc,usdcImpl:T.usdcImpl,aave:T.aave,aaveImpl:T.impl,ethFeed:T.ethFeed,usdFeed:T.usdFeed})){const c=await sourceCode(a);if(c==='0x')throw Error(`${name} source runtime absent`);codeHashes[name]=keccak256(toBytes(c));}
  if(!aaveOnly&&codeHashes.factory!==T.factoryHash)throw Error('Uniswap factory runtime does not match Sourcify source-evidence hash');
  const lc=async(a:string)=>rpc(url,'eth_getCode',[a,'latest'],false,localGuard);
  for(const [name,a]of Object.entries(aaveOnly?{calibur:CALIBUR,weth:T.weth,aave:T.aave,aaveImpl:T.impl}:{calibur:CALIBUR,router:T.router,factory:T.factory,pool:T.pool,weth:T.weth,usdc:T.usdc,usdcImpl:T.usdcImpl,aave:T.aave,aaveImpl:T.impl,ethFeed:T.ethFeed,usdFeed:T.usdFeed}))if(keccak256(toBytes(await lc(a)))!==codeHashes[name])throw Error(`${name} local/source runtime mismatch`);
  let usdcSlotLocal='';
  if(!aaveOnly){const usdcSlotSource=String(await read('eth_getStorageAt',[T.usdc,T.usdcImplSlot,'0x'+forkBlock.toString(16)])).toLowerCase();usdcSlotLocal=String(await rpc(url,'eth_getStorageAt',[T.usdc,T.usdcImplSlot,'0x'+forkBlock.toString(16)],false,localGuard)).toLowerCase();if(usdcSlotSource!==usdcSlotLocal||'0x'+usdcSlotSource.slice(-40)!==T.usdcImpl.toLowerCase())throw Error('USDC ZeppelinOS implementation slot mismatch at fork block');if(codeHashes.usdcImpl!==T.usdcImplHash)throw Error('USDC implementation source runtime hash mismatch');}
  const chain=defineChain({id:CHAIN_ID,name:'Isolated Anvil fork',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:[url]}}});const pub=createPublicClient({chain,transport:http(url)});
  const poolFor=await pub.readContract({address:T.factory,abi:factoryAbi,functionName:'getPool',args:[T.weth,T.usdc,500]});if(poolFor.toLowerCase()!==T.pool.toLowerCase())throw Error('fee-500 factory pool identity mismatch');
  const [t0,t1,fee,factory,liq]=await Promise.all(['token0','token1','fee','factory','liquidity'].map(functionName=>pub.readContract({address:T.pool,abi:poolAbi,functionName:functionName as any}))) as any[];
  if(t0.toLowerCase()!==T.usdc.toLowerCase()||t1.toLowerCase()!==T.weth.toLowerCase()||Number(fee)!==500||factory.toLowerCase()!==T.factory.toLowerCase()||liq===0n)throw Error('pool getters do not match reviewed identity');
  const accounts=await rpc(url,'eth_accounts',[],false,localGuard);const owner=accounts[0];if(!owner)throw Error('Anvil test identity unavailable');
  const mut=async(method:string,params:unknown[])=>rpc(url,method,params,false,localGuard);
  await mut('anvil_impersonateAccount',[owner]);await mut('anvil_setBalance',[owner,'0x56BC75E2D63100000']);
  await mut('anvil_setCode',[owner,'0xef0100'+CALIBUR.slice(2).toLowerCase()]);
  const send=async(to:string,data:string,value='0x0')=>{const h=await mut('eth_sendTransaction',[{from:owner,to,data,value}]);const rec=await waitReceipt(h,localGuard,url);if(rec.status!=='0x1'){let why='reverted';try{const tr=await rpc(url,'debug_traceTransaction',[h,{}],false,localGuard);why=String(tr?.revertReason||tr?.returnValue||why).slice(0,180);}catch{}throw Error(`local transaction reverted ${h}: ${why}`);}return {hash:h,gasUsed:BigInt(rec.gasUsed).toString(),blockHash:rec.blockHash};};
  const wait=async()=>{for(let i=0;i<50;i++){const c=await lc(owner);if(c==='0xef0100'+CALIBUR.slice(2).toLowerCase())return;await delay(50);}throw Error('delegation designator not installed');};await wait();
  const wethBal=()=>pub.readContract({address:T.weth,abi:erc20,functionName:'balanceOf',args:[owner]});const usdcBal=()=>pub.readContract({address:T.usdc,abi:erc20,functionName:'balanceOf',args:[owner]});
  const dep=await send(T.weth,encodeFunctionData({abi:parseAbi(['function deposit() payable']),functionName:'deposit'}),'0x2386f26fc10000');
  if(aaveOnly){
    const aaveSlotSource=String(await read('eth_getStorageAt',[T.aave,proxySlot,'0x'+forkBlock.toString(16)])).toLowerCase();const aaveSlotLocal=String(await rpc(url,'eth_getStorageAt',[T.aave,proxySlot,'0x'+forkBlock.toString(16)],false,localGuard)).toLowerCase();if(aaveSlotSource!==aaveSlotLocal||'0x'+aaveSlotLocal.slice(-40)!==T.impl.toLowerCase())throw Error('Aave implementation slot mismatch at pinned fork block');
    const reserve=await pub.readContract({address:T.aave,abi:aaveAbi,functionName:'getReserveData',args:[T.weth]}) as any;const aToken=reserve[8] as `0x${string}`,stableDebtToken=reserve[9] as `0x${string}`,variableDebtToken=reserve[10] as `0x${string}`;if(!aToken||!stableDebtToken||!variableDebtToken||await lc(aToken)==='0x'||await lc(stableDebtToken)==='0x'||await lc(variableDebtToken)==='0x')throw Error('Aave WETH reserve aToken/debt token code missing');
    const initialWeth=await wethBal(),initialAToken=await pub.readContract({address:aToken,abi:erc20,functionName:'balanceOf',args:[owner]}),initialStableDebt=await pub.readContract({address:stableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]}),initialVariableDebt=await pub.readContract({address:variableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]});const amount=5n*10n**15n;if(initialWeth<amount)throw Error('local WETH deposit did not fund exact Aave amount');
    const tracePath='/private/var/folders/d5/bq_4hlms3xb3f03m4w9y582h0000gp/T/opencode/defi-forks-20261002/aave-local-traces';await mkdir(tracePath,{recursive:true});
    const batchData=(calls:any[])=>encodeFunctionData({abi:executeAbi,functionName:'execute',args:[[calls.map(c=>[c.to,0n,c.data]),true] as any]});
    const capture=async(phase:'supply'|'withdraw',to:string,data:string)=>{const hash=await mut('eth_sendTransaction',[{from:owner,to,data}]);const receipt=await waitReceipt(hash,localGuard,url);let trace:any;try{trace=await rpc(url,'debug_traceTransaction',[hash,{tracer:'callTracer',tracerConfig:{onlyTopCall:false}}],false,localGuard);}catch(callTraceError){try{trace={fallback:'opcode-trace',trace:await rpc(url,'debug_traceTransaction',[hash,{disableStorage:true,disableMemory:true}],false,localGuard),callTracerError:String(callTraceError).slice(0,160)};}catch(fallbackError){trace={traceUnavailable:true,errors:[String(callTraceError).slice(0,160),String(fallbackError).slice(0,160)]};}}
      const record={phase,from:owner,to,calldata:data,topLevelSelector:data.slice(0,10),transactionHash:hash,receipt:{status:receipt.status,gasUsed:receipt.gasUsed,blockHash:receipt.blockHash},trace};await writeFile(`${tracePath}/${phase}-${hash}.json`,JSON.stringify(record,null,2));proof.aave={...(proof.aave||{}),[phase]:{...record,traceFile:`${tracePath}/${phase}-${hash}.json`}};return record;};
    const supply=encodeFunctionData({abi:aaveAbi,functionName:'supply',args:[T.weth,amount,owner,0]});const supplyBatch=batchData([{to:T.weth,data:encodeFunctionData({abi:erc20,functionName:'approve',args:[T.aave,amount]})},{to:T.aave,data:supply},{to:T.weth,data:encodeFunctionData({abi:erc20,functionName:'approve',args:[T.aave,0n]})}]);
    proof={status:'partial',chainId:CHAIN_ID,sourceChainId:SOURCE_CHAIN,forkBlock,forkHash,owner,codeHashes,aave:{forkImplSlot:aaveSlotLocal,implementation:T.impl,aToken,stableDebtToken,variableDebtToken,initialWeth:initialWeth.toString(),initialAToken:initialAToken.toString(),initialStableDebt:initialStableDebt.toString(),initialVariableDebt:initialVariableDebt.toString(),amount:amount.toString(),phases:[]},coverageGap:'Aave execution pending'};
    const supRecord=await capture('supply',owner,supplyBatch);if(supRecord.receipt.status!=='0x1'){proof.aave.result='supply batch reverted; inspect persisted trace; no retry';proof.coverageGap='Aave supply did not succeed; withdrawal not attempted';process.exitCode=1;return;}
    const afterSupplyWeth=await wethBal(),afterSupplyAToken=await pub.readContract({address:aToken,abi:erc20,functionName:'balanceOf',args:[owner]}),afterSupplyStableDebt=await pub.readContract({address:stableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]}),afterSupplyVariableDebt=await pub.readContract({address:variableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]}),supplyAllowance=await pub.readContract({address:T.weth,abi:erc20,functionName:'allowance',args:[owner,T.aave]});if(afterSupplyWeth!==initialWeth-amount||afterSupplyAToken<=initialAToken||afterSupplyStableDebt!==0n||afterSupplyVariableDebt!==0n||supplyAllowance!==0n)throw Error('Aave supply post-state assertions failed');
    const supplyPostState={wethSpent:(initialWeth-afterSupplyWeth).toString(),aTokenIncrease:(afterSupplyAToken-initialAToken).toString(),aTokenBalance:afterSupplyAToken.toString(),stableDebt:afterSupplyStableDebt.toString(),variableDebt:afterSupplyVariableDebt.toString(),allowance:supplyAllowance.toString()};proof.aave.supplyPostState=supplyPostState;const supplyFile=proof.aave.supply.traceFile;const supplyArtifact=JSON.parse(await readFile(supplyFile,'utf8'));supplyArtifact.postState=supplyPostState;await writeFile(supplyFile,JSON.stringify(supplyArtifact,null,2));
    const withdrawAmount=afterSupplyAToken/2n;if(withdrawAmount<=0n||withdrawAmount>25n*10n**16n)throw Error('half-position withdrawal amount outside positive configured bound');proof.aave.withdrawAmount=withdrawAmount.toString();
    const scaledBefore=await pub.readContract({address:aToken,abi:scaledBalanceAbi,functionName:'scaledBalanceOf',args:[owner]});const indexBefore=await pub.readContract({address:T.aave,abi:aaveAbi,functionName:'getReserveNormalizedIncome',args:[T.weth]});
    const withdraw=encodeFunctionData({abi:aaveAbi,functionName:'withdraw',args:[T.weth,withdrawAmount,owner]});const withdrawBatch=batchData([{to:T.aave,data:withdraw}]);const wdRecord=await capture('withdraw',owner,withdrawBatch);if(wdRecord.receipt.status!=='0x1'){proof.aave.result='supply passed; half-position withdrawal batch reverted; inspect persisted trace';proof.coverageGap='Aave partial withdrawal reverted; no retry';process.exitCode=1;return;}
    // (withdrawAmount is selected above from the measured half nominal position.) The actual
    // mutating tx was already sent; these reads are immediately after it to measure its effects.
    const finalWeth=await wethBal(),finalAToken=await pub.readContract({address:aToken,abi:erc20,functionName:'balanceOf',args:[owner]}),finalScaled=await pub.readContract({address:aToken,abi:scaledBalanceAbi,functionName:'scaledBalanceOf',args:[owner]}),indexAfter=await pub.readContract({address:T.aave,abi:aaveAbi,functionName:'getReserveNormalizedIncome',args:[T.weth]}),finalStableDebt=await pub.readContract({address:stableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]}),finalVariableDebt=await pub.readContract({address:variableDebtToken,abi:erc20,functionName:'balanceOf',args:[owner]}),withdrawAllowance=await pub.readContract({address:T.weth,abi:erc20,functionName:'allowance',args:[owner,T.aave]});const wethReceived=finalWeth-afterSupplyWeth,scaledBurn=scaledBefore-finalScaled,nominalScaledBurn=(scaledBurn*indexAfter+10n**27n/2n)/10n**27n;const withdrawPostState={requested:withdrawAmount.toString(),wethIncrease:wethReceived.toString(),aTokenBefore:afterSupplyAToken.toString(),aTokenAfter:finalAToken.toString(),aTokenNominalDecrease:(afterSupplyAToken-finalAToken).toString(),scaledBefore:scaledBefore.toString(),scaledAfter:finalScaled.toString(),scaledBurn:scaledBurn.toString(),normalizedIncomeBefore:indexBefore.toString(),normalizedIncomeAfter:indexAfter.toString(),scaledBurnNominalAtFinalIndex:nominalScaledBurn.toString(),stableDebt:finalStableDebt.toString(),variableDebt:finalVariableDebt.toString(),allowance:withdrawAllowance.toString()};proof.aave.withdrawPostState=withdrawPostState;const withdrawFile=proof.aave.withdraw.traceFile;const withdrawArtifact=JSON.parse(await readFile(withdrawFile,'utf8'));withdrawArtifact.postState=withdrawPostState;await writeFile(withdrawFile,JSON.stringify(withdrawArtifact,null,2));
    if(wethReceived!==withdrawAmount||scaledBurn<=0n||nominalScaledBurn<withdrawAmount-1000000n||nominalScaledBurn>withdrawAmount+1000000n||finalStableDebt!==0n||finalVariableDebt!==0n||withdrawAllowance!==0n)throw Error('Aave withdraw post-state assertions failed');proof.aave.result='supply and half-position withdraw passed';proof.proofs=['eth-aave-weth-supply','eth-aave-weth-partial-withdraw'];proof.coverageGap='';return;
  }
  const amount=10n**16n;if(await wethBal()<amount)throw Error('canonical WETH deposit did not credit owner');
  const [ed,ud,er,ur]=await Promise.all([pub.readContract({address:T.ethFeed,abi:feedAbi,functionName:'decimals'}),pub.readContract({address:T.usdFeed,abi:feedAbi,functionName:'decimals'}),pub.readContract({address:T.ethFeed,abi:feedAbi,functionName:'latestRoundData'}),pub.readContract({address:T.usdFeed,abi:feedAbi,functionName:'latestRoundData'})]) as any[];
  const now=BigInt((await pub.getBlock()).timestamp);for(const [r,d]of [[er,ed],[ur,ud]])if(Number(d)!==8||r[1]<=0n||r[3]===0n||r[3]>now||now-r[3]>86400n)throw Error('Chainlink price answer invalid/stale');
  const numerator=amount*er[1]*10n**(BigInt(ud)+6n)*9900n,denominator=ur[1]*10n**(BigInt(ed)+18n)*10000n;const minOut=(numerator+denominator-1n)/denominator;
   const batchData=(calls:any[])=>encodeFunctionData({abi:executeAbi,functionName:'execute',args:[[calls.map(c=>[c.to,0n,c.data]),true] as any]});
   const batch=async(calls:any[])=>send(owner,batchData(calls));
   const approve=(token:string,n:bigint)=>encodeFunctionData({abi:erc20,functionName:'approve',args:[T.router,n]});
   const call=(tokenIn:string,tokenOut:string,fee:number,recipient:string,amountIn:bigint,amountOutMinimum:bigint,until:bigint)=>encodeFunctionData({abi:routerAbi,functionName:'exactInputSingle',args:[[tokenIn,tokenOut,fee,recipient,until,amountIn,amountOutMinimum,0n] as any]});
   const allowance=(token:string)=>pub.readContract({address:token as `0x${string}`,abi:erc20,functionName:'allowance',args:[owner,T.router]});
   const floor=async(tokenIn:string,tokenOut:string,q:bigint,tin:number,tout:number)=>{const ain=tokenIn.toLowerCase()===T.weth.toLowerCase()?er[1]:ur[1],aout=tokenOut.toLowerCase()===T.weth.toLowerCase()?er[1]:ur[1];const di=tokenIn.toLowerCase()===T.weth.toLowerCase()?Number(ed):Number(ud),dout=tokenOut.toLowerCase()===T.weth.toLowerCase()?Number(ed):Number(ud);const den=aout*10n**BigInt(di+tin)*10000n;const num=q*ain*10n**BigInt(dout+tout)*9900n;return (num+den-1n)/den;};
   const beforeU=await wethBal(),beforeS=await usdcBal();const swap=call(T.weth,T.usdc,500,owner,amount,minOut,now+120n);const swapReceipt=await batch([{to:T.weth,data:approve(T.weth,amount)},{to:T.router,data:swap},{to:T.weth,data:approve(T.weth,0n)}]);const afterU=await wethBal(),afterS=await usdcBal();const wethAllow=await allowance(T.weth);if(beforeU-afterU!==amount||afterS<=beforeS||wethAllow!==0n)throw Error('forward swap post-state assertions failed');
   const reverseAmount=afterS-beforeS<10_000_000n?(afterS-beforeS)/2n:10_000_000n;if(reverseAmount<=0n)throw Error('insufficient positive USDC for reverse fixture');const reverseMin=await floor(T.usdc,T.weth,reverseAmount,6,18);const revBeforeU=await wethBal(),revBeforeS=await usdcBal();const reverseCall=call(T.usdc,T.weth,500,owner,reverseAmount,reverseMin,BigInt((await pub.getBlock()).timestamp)+120n);const reverseReceipt=await batch([{to:T.usdc,data:approve(T.usdc,reverseAmount)},{to:T.router,data:reverseCall},{to:T.usdc,data:approve(T.usdc,0n)}]);const revAfterU=await wethBal(),revAfterS=await usdcBal();const usdcAllow=await allowance(T.usdc);if(revBeforeS-revAfterS!==reverseAmount||revAfterU-revBeforeU<reverseMin||usdcAllow!==0n)throw Error('reverse swap post-state assertions failed');
   // Protocol-level negative vectors must revert atomically and preserve token balances/allowances.
   const rejected=async(data:string,label:string)=>{const u0=await wethBal(),s0=await usdcBal(),wu0=await allowance(T.weth),su0=await allowance(T.usdc);const h=await mut('eth_sendTransaction',[{from:owner,to:owner,data}]);const rec=await waitReceipt(h,localGuard,url);if(rec.status!=='0x0')throw Error(`${label} unexpectedly succeeded (${h})`);const u1=await wethBal(),s1=await usdcBal(),wu1=await allowance(T.weth),su1=await allowance(T.usdc);if(u0!==u1||s0!==s1||wu0!==wu1||su0!==su1)throw Error(`${label} failed to roll back state`);return {hash:h,status:rec.status,blockHash:rec.blockHash,balancesAndAllowancesUnchanged:true};};
   const huge=(1n<<256n)-1n;const highMinCall=call(T.weth,T.usdc,500,owner,amount,huge,BigInt((await pub.getBlock()).timestamp)+120n);const minOutRevert=await rejected(batchData([{to:T.weth,data:approve(T.weth,amount)},{to:T.router,data:highMinCall},{to:T.weth,data:approve(T.weth,0n)}]),'impossible minimum output');
   const latestTime=BigInt((await pub.getBlock()).timestamp);const expired=call(T.weth,T.usdc,500,owner,amount,1n,latestTime-1n);const deadlineRevert=await rejected(batchData([{to:T.weth,data:approve(T.weth,amount)},{to:T.router,data:expired},{to:T.weth,data:approve(T.weth,0n)}]),'expired deadline');
   proof={status:'partial',chainId:CHAIN_ID,sourceChainId:SOURCE_CHAIN,forkBlock,forkHash,owner,codeHashes,usdcProxy:{implementationSlot:T.usdcImplSlot,implementation:T.usdcImpl,slotAtFork:usdcSlotLocal},pool:{address:T.pool,fee:Number(fee),liquidity:liq.toString()},forward:{deposit:dep,receipt:swapReceipt,amountIn:amount.toString(),minimumOut:minOut.toString(),outputDelta:(afterS-beforeS).toString(),allowance:wethAllow.toString()},reverse:{receipt:reverseReceipt,amountIn:reverseAmount.toString(),minimumOut:reverseMin.toString(),outputDelta:(revAfterU-revBeforeU).toString(),allowance:usdcAllow.toString()},negativeVectors:{impossibleMinimum:minOutRevert,expiredDeadline:deadlineRevert},proofs:['eth-weth-usdc-forward','eth-usdc-weth-reverse','eth-calibur-atomic-minout-revert','eth-calibur-atomic-deadline-revert'],coverageGap:'Aave supply/withdraw unproven; prior batch revert selector phase is unresolved; no retry performed'};
  }catch(e){proof.status='failed';proof.failure=String((e as Error).message||'unknown').slice(0,240);process.exitCode=1;}finally{if(child&&child.exitCode===null){child.kill('SIGTERM');await Promise.race([new Promise<void>(r=>child!.once('exit',()=>r())),delay(2500)]);if(child.exitCode===null)child.kill('SIGKILL');}process.stdout.write(JSON.stringify(proof)+'\n');}
}
async function waitReceipt(hash:string,guard:()=>Promise<void>,url:string):Promise<any>{for(let i=0;i<80;i++){const r=await rpc(url,'eth_getTransactionReceipt',[hash],false,guard);if(r)return r;await delay(100);}throw Error('local transaction receipt timeout');}
if(require.main===module)void main();
