import { validatePolymarketClobOrder, polymarketOrderDigest, polymarketWrapperDigest, polymarketDomainSeparator } from './polymarket-clob-order';
import { buildPolymarketPoly1271Envelope, polymarketOrderContentsHash, POLYMARKET_ORDER_TYPE } from './polymarket-poly1271-envelope';

const now = 1_700_000_000_000;
const orderFields = () => [['salt','uint256'],['maker','address'],['signer','address'],['tokenId','uint256'],['makerAmount','uint256'],['takerAmount','uint256'],['side','uint8'],['signatureType','uint8'],['timestamp','uint256'],['metadata','bytes32'],['builder','bytes32']].map(([name,type])=>({name,type}));
const wrapperFields = () => [['contents','Order'],['name','string'],['version','string'],['chainId','uint256'],['verifyingContract','address'],['salt','bytes32']].map(([name,type])=>({name,type}));
const wallet = '0x1111111111111111111111111111111111111111';
const sample = () => ({domain:{name:'Polymarket CTF Exchange',version:'2',chainId:137,verifyingContract:'0xE111180000d2663C0091e4f400237545B87B996B'},types:{Order:orderFields(),TypedDataSign:wrapperFields()},primaryType:'TypedDataSign',message:{contents:{salt:'1700000000000000000',maker:wallet,signer:wallet,tokenId:'2',makerAmount:'3',takerAmount:'4',side:0,signatureType:3,timestamp:String(now),metadata:`0x${'00'.repeat(32)}`,builder:`0x${'ff'.repeat(32)}`},name:'DepositWallet',version:'1',chainId:137,verifyingContract:wallet,salt:`0x${'00'.repeat(32)}`}});
// Golden generated by ExchangeOrderBuilderV2.buildSignedOrder from @polymarket/clob-client-v2@1.2.0.
// Registry tarball integrity: sha512-LmqNqKxp3EZetixMytW2RH4X60pfh8YHJKeRxCsZiLuegeUpXS4ggsQgPdRP4h7JCWB0DdygxjpEBjBDWvOOiQ==.
const SDK_GOLDEN = {
  signature:'0x5003cfe77edce84164f4637ecf8d8617d796e7b00ba89e45b0033bca19f9c27e7a0ec44704aa98042a55c5d9262bccd0ce02a1a4186c9420daaa360ab80591e61c3264e159346253e26a64e00b69032db0e7d32f94628de3e6eecb50304d7af3d289af0425bddcf017a75d086613218ca9923c7149db17cf87299bdc665e29c28e',
  contentsHash:'0x89af0425bddcf017a75d086613218ca9923c7149db17cf87299bdc665e29c28e',
  appDomain:'0x3264e159346253e26a64e00b69032db0e7d32f94628de3e6eecb50304d7af3d2',
  orderDigest:'0x4be0004caa485bd916d20e043ba5e3f0e33e6b54ce69a383a337cee356dca3c2',
  wrapperDigest:'0x3167778c1760864922d4150ea0f51e408db4f61ce8585d5ddde8194dd33b7eef',
};
describe('Polymarket CLOB order signing',()=>{
  it('accepts protocol exact input and constructs a non-bare Order digest envelope',()=>{
    const p=validatePolymarketClobOrder(sample(),now);
    expect(p.message.verifyingContract).toBe(wallet);
    const sig=SDK_GOLDEN.signature.slice(0,132) as `0x${string}`;
    const envelope=buildPolymarketPoly1271Envelope(p,sig);
    expect(envelope.slice(0,132)).toBe(sig);
    expect(envelope.slice(132,196)).toBe(SDK_GOLDEN.appDomain.slice(2));
    expect(polymarketOrderContentsHash(p)).toBe(SDK_GOLDEN.contentsHash);
    expect(envelope).toBe(`${sig}${SDK_GOLDEN.appDomain.slice(2)}${SDK_GOLDEN.contentsHash.slice(2)}${Buffer.from(POLYMARKET_ORDER_TYPE).toString('hex')}00ba`);
    expect(polymarketWrapperDigest(p)).toBe(SDK_GOLDEN.wrapperDigest);
    expect(polymarketDomainSeparator(p)).toBe(SDK_GOLDEN.appDomain);
    // Independent viem reference for ordinary EIP-712 Order digest (same SDK v1.2.0 order fields).
    expect(polymarketOrderDigest(p)).toBe(SDK_GOLDEN.orderDigest);
    expect(polymarketOrderDigest(p)).not.toBe(polymarketWrapperDigest(p));
    expect(envelope.length).toBe(132+64+64+POLY_TYPE_LENGTH*2+4);
  });
  it('deep-freezes the complete canonical payload used by digest and caller validation',()=>{
    const p=validatePolymarketClobOrder(sample(),now);
    const digest=polymarketOrderDigest(p);
    expect(Object.isFrozen(p)).toBe(true);
    expect(Object.isFrozen(p.domain)).toBe(true);
    expect(Object.isFrozen(p.message)).toBe(true);
    expect(Object.isFrozen(p.message.contents)).toBe(true);
    expect(Object.isFrozen(p.types)).toBe(true);
    for (const type of Object.values(p.types)) {
      expect(Object.isFrozen(type)).toBe(true);
      for (const field of type) expect(Object.isFrozen(field)).toBe(true);
    }
    expect(()=>((p.message.contents as any).makerAmount='999')).toThrow();
    expect(polymarketOrderDigest(p)).toBe(digest);
    const modified=sample(); modified.message.contents.makerAmount='999';
    expect(()=>validatePolymarketClobOrder(modified,now)).not.toThrow();
    expect(polymarketOrderDigest(validatePolymarketClobOrder(modified,now))).not.toBe(digest);
    const extra=sample() as any; extra.message.contents.extra='x';
    expect(()=>validatePolymarketClobOrder(extra,now)).toThrow();
  });
  it.each([
    ['extra order field',(x:any)=>{x.message.contents.extra=1;return x},'eoa'],
    ['field order',(x:any)=>{x.types.Order.reverse();return x},'eoa'],
    ['domain',(x:any)=>{x.domain.chainId=1;return x},'eoa'],
    ['maker mismatch',(x:any)=>{x.message.contents.signer='0x2222222222222222222222222222222222222222';return x},'eoa'],
    ['signature type',(x:any)=>{x.message.contents.signatureType=2;return x},'eoa'],
    ['zero amount',(x:any)=>{x.message.contents.makerAmount='0';return x},'eoa'],
    ['overflow',(x:any)=>{x.message.contents.salt=(1n<<256n).toString();return x},'eoa'],
    ['uint8 overflow',(x:any)=>{x.message.contents.side=256;return x},'eoa'],
    ['stale timestamp',(x:any)=>{x.message.contents.timestamp=String(now+300001);return x},'eoa'],
    ['unsafe numeric',(x:any)=>{x.message.contents.tokenId=Number.MAX_SAFE_INTEGER+1;return x},'eoa'],
    ['bytes32',(x:any)=>{x.message.contents.builder='0x1234';return x},'eoa'],
    ['wrong wrapper order',(x:any)=>{x.types.TypedDataSign.reverse();return x},'eoa'],
    ['wrapper salt',(x:any)=>{x.message.salt='0x'+'01'.repeat(32);return x},'eoa'],
  ])('rejects %s',(_label,mutate)=>{
    expect(()=>validatePolymarketClobOrder((mutate as any)(sample()),now)).toThrow();
  });
  it.each(['0x1234', `0x${'11'.repeat(64)}02`])('rejects malformed signature %s', (signature) => {
    const p=validatePolymarketClobOrder(sample(),now);
    expect(()=>buildPolymarketPoly1271Envelope(p,signature as `0x${string}`)).toThrow();
  });
});
const POLY_TYPE_LENGTH = 186;
