import { createCatalogUpdateCliReport } from '../../../../scripts/defi-catalog/update-cli-report';
import type { CatalogUpdatePlan } from './catalog-update';

const candidate=(address:string,id:string,admitted:boolean)=>({sourcePath:'data/defi-catalog/updates/test/sources/x.json',familyId:'comet',familyVersion:'v1',chainId:1,contract:address,signature:'supply(address,uint256)',selector:'0x12345678',abiHash:`0x${'a'.repeat(64)}`,sourceRefs:['implementation','interface'],fn:{status:'inactive',capabilityId:id},admitted});
const plan={schemaVersion:1,baseline:{path:'data/defi-catalog/v9/catalog.json',rawSha256:'b'.repeat(64),manifestHash:`0x${'c'.repeat(64)}`},sources:[],admissions:[{sourcePath:'data/defi-catalog/updates/test/sources/x.json',familyId:'comet',familyVersion:'v1',chainId:1,contract:'0x0000000000000000000000000000000000000001',signature:'supply(address,uint256)',selector:'0x12345678',abiHash:`0x${'a'.repeat(64)}`,capabilityId:'stable:comet:supply',sourceRefs:['implementation','interface'],executionScope:null,executionScopeHash:null,authorityReview:{classification:'ordinary-direct' as const,sourceRefs:['implementation'],evidence:'reviewed'}}],deactivations:[]} as unknown as CatalogUpdatePlan;
const prepared:any={candidates:[candidate('0x0000000000000000000000000000000000000001','candidate:one',true),candidate('0x0000000000000000000000000000000000000002','candidate:two',false)],previewCatalog:{chains:[{contracts:[{functions:[{},{}]}]}]},projectedCatalog:{chains:[{contracts:[{functions:[{},{}]}]}]},diff:{added:['candidate:one','candidate:two']},projectedDiff:{added:['stable:comet:supply']},sourceDigests:[{sourcePath:'source',canonicalSha256:'d'.repeat(64)}],deactivationProposals:[]};

describe('generic catalog CLI report projection',()=>{
  it('reports every inactive source candidate and resolves only exact admitted IDs',()=>{const report=createCatalogUpdateCliReport(prepared,plan,673);expect(report.candidates).toHaveLength(2);expect(report.candidates.map(x=>x.status)).toEqual(['inactive','inactive']);expect(report.candidates.map(x=>x.admitted)).toEqual([true,false]);expect(report.candidates.map(x=>x.projectedCapabilityId)).toEqual(['stable:comet:supply',null]);expect(report.candidates[0].candidateCapabilityId).toBe('candidate:one');expect(report.previewDiff.added).toEqual(['candidate:one','candidate:two']);expect(report.projectedDiff.added).toEqual(['stable:comet:supply']);expect(report.counts.candidates).toBe(2);expect(report.writePerformed).toBe(false);});
  it('rejects inconsistent identity or falsely active preview functions',()=>{const mismatch={...prepared,candidates:[{...prepared.candidates[0],contract:'0x0000000000000000000000000000000000000009'}]};expect(()=>createCatalogUpdateCliReport(mismatch,plan,673)).toThrow(/mapping/);const active={...prepared,candidates:[{...prepared.candidates[1],fn:{status:'active',capabilityId:'candidate:two'}}]};expect(()=>createCatalogUpdateCliReport(active,{...plan,admissions:[]} as CatalogUpdatePlan,673)).toThrow(/inactive/);});
});
