import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { buildReviewedManifest } from '../registry/defi-manifest';
import { canonicalSourceSha256, validateCatalogDocument, compileSourceSnapshotBindings } from './catalog-generator';
import { prepareCatalogUpdate, validateUpdatePlan, fullCatalogFunctionSha256, assembleCatalogUpdate } from './catalog-update';

const root=process.cwd(), baselinePath='data/defi-catalog/v9/catalog.json';
const raw=readFileSync(resolve(root,baselinePath));
const baseline=validateCatalogDocument(JSON.parse(raw.toString('utf8')) as unknown);
const baselinePin={path:baselinePath,rawSha256:createHash('sha256').update(raw).digest('hex'),manifestHash:buildReviewedManifest([baseline]).manifestHash};
const updatePath='data/defi-catalog/updates/test/sources/sample.json';
const snapshot=(addresses=['0x0000000000000000000000000000000000000001','0x0000000000000000000000000000000000000002'])=>({schemaVersion:1,sources:[{sourceId:'verified-interface',url:'https://example.invalid/abi.json',retrievedAtUtc:'2026-10-05',evidence:'fixture'}],unresolved:[],families:[{familyId:'ordinary-test',familyVersion:'release-1',contracts:addresses.map(address=>({chainId:1,address,status:'inactive',contractName:'Ordinary',sourceRefs:['verified-interface'],abiFunctions:[{type:'function',name:'ping',stateMutability:'nonpayable',inputs:[],outputs:[],status:'inactive',sourceRefs:['verified-interface']}]}))}]});
const basePlan=(doc:unknown)=>({schemaVersion:1,baseline:{...baselinePin},sources:[{path:updatePath,canonicalSha256:canonicalSourceSha256(doc)}],admissions:[],deactivations:[]});
const fixture=(doc:unknown,ids:string[])=>{const bindings=compileSourceSnapshotBindings(doc,updatePath);return {...basePlan(doc),admissions:bindings.map((b,i)=>({sourcePath:updatePath,familyId:b.familyId,familyVersion:b.familyVersion,chainId:b.chainId,contract:b.contract,signature:b.signature,selector:b.selector,abiHash:b.abiHash,capabilityId:ids[i],sourceRefs:[...b.sourceRefs],executionScope:null,executionScopeHash:null,authorityReview:{classification:'ordinary-direct',sourceRefs:[b.sourceRefs[0]],evidence:'Human confirmed this snapshot is the direct contract interface.'}}))};};

describe('generic catalog update core',()=>{
  it('validates baseline SHA formats and strict plan schema',()=>{expect(validateUpdatePlan(basePlan(snapshot())).schemaVersion).toBe(1);expect(()=>validateUpdatePlan({...basePlan(snapshot()),extra:true})).toThrow();const p:any=basePlan(snapshot());p.baseline.manifestHash='a'.repeat(64);expect(()=>validateUpdatePlan(p)).toThrow();});
  it('requires source pins in selected plan folder and unique paths',()=>{const p:any=basePlan(snapshot());p.sources[0].path='data/defi-catalog/updates/elsewhere/sources/x.json';expect(()=>validateUpdatePlan(p,'data/defi-catalog/updates/test/plan.json')).toThrow();p.sources[0].path=updatePath;p.sources.push({...p.sources[0]});expect(()=>validateUpdatePlan(p)).toThrow();});
  it('binds exact target, family version, selector, complete ABI and source refs',()=>{const doc=snapshot();const plan:any=fixture(doc,['ordinary:test:one','ordinary:test:two']);const preparation=prepareCatalogUpdate({chains:baseline.chains},plan,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256);expect(preparation.candidates).toHaveLength(2);expect(preparation.candidates.map(x=>x.fn.status)).toEqual(['inactive','inactive']);expect(preparation.projectedDiff.added).toHaveLength(2);expect(preparation.diff.added).toHaveLength(2);expect(preparation.projectedCatalog.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions)).filter(f=>plan.admissions.some((a:any)=>a.capabilityId===f.capabilityId)).every(f=>f.status==='active')).toBe(true);
    plan.admissions[0].familyVersion='release-2';expect(()=>prepareCatalogUpdate({chains:baseline.chains},plan,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow();
    const forged:any=fixture(doc,['ordinary:test:one','ordinary:test:two']);forged.admissions[0].sourceRefs=['forged'];forged.admissions[0].authorityReview.sourceRefs=['forged'];expect(()=>prepareCatalogUpdate({chains:baseline.chains},forged,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow();
  });
  it('previews every candidate inactive while projecting only a partial explicit admission set',()=>{const doc=snapshot(),plan:any=fixture(doc,['stable:one','stable:two']);plan.admissions.pop();const prepared=prepareCatalogUpdate({chains:baseline.chains},plan,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256);expect(prepared.candidates).toHaveLength(2);expect(prepared.candidates.every(c=>c.fn.status==='inactive')).toBe(true);expect(prepared.candidates.map(c=>c.admitted)).toEqual([true,false]);expect(prepared.diff.added).toHaveLength(2);expect(prepared.projectedDiff.added).toEqual(['stable:one']);expect(prepared.projectedCatalog.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions))).toHaveLength(674);});
  it('supports the same canonical signature on two distinct target contracts without aliasing',()=>{const doc=snapshot();const bindings=compileSourceSnapshotBindings(doc,updatePath);expect(bindings.map(x=>x.signature)).toEqual(['ping()','ping()']);expect(new Set(bindings.map(x=>x.contract)).size).toBe(2);expect(fixture(doc,['stable:1','stable:2']).admissions).toHaveLength(2);});
  it('keeps overloads distinct and rejects ABI changes in parameters, outputs, and mutability',()=>{const doc:any=snapshot(['0x0000000000000000000000000000000000000003']);doc.families[0].contracts[0].abiFunctions.push({type:'function',name:'ping',stateMutability:'view',inputs:[{name:'n',type:'uint256',internalType:'uint256'}],outputs:[{name:'answer',type:'uint256',internalType:'uint256'}],status:'inactive',sourceRefs:['verified-interface']});const bindings=compileSourceSnapshotBindings(doc,updatePath);expect(bindings.map(x=>x.signature)).toEqual(['ping()','ping(uint256)']);const changed:any=snapshot(['0x0000000000000000000000000000000000000003']);changed.families[0].contracts[0].abiFunctions[0].outputs=[{name:'answer',type:'uint256',internalType:'uint256'}];expect(compileSourceSnapshotBindings(changed,updatePath)[0].abiHash).not.toBe(bindings[0].abiHash);});
  it('rejects source digest, raw baseline pin, manifest and inactive-source tampering',()=>{const doc=snapshot(),p:any=fixture(doc,['stable:1','stable:2']);p.sources[0].canonicalSha256='0'.repeat(64);expect(()=>prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow();p.sources[0].canonicalSha256=canonicalSourceSha256(doc);expect(()=>prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}], '0'.repeat(64))).toThrow();const active:any=snapshot();active.families[0].contracts[0].status='candidate';expect(()=>compileSourceSnapshotBindings(active,updatePath)).toThrow();});
  it('rejects recursive bytes, scopes, duplicate IDs and new selector aliases',()=>{const doc:any=snapshot();doc.families[0].contracts[0].abiFunctions[0].inputs=[{name:'arg',type:'tuple[]',components:[{name:'data',type:'bytes4'}]}];const b=compileSourceSnapshotBindings(doc,updatePath)[0];const p:any={...basePlan(doc),admissions:[{sourcePath:updatePath,familyId:b.familyId,familyVersion:b.familyVersion,chainId:b.chainId,contract:b.contract,signature:b.signature,selector:b.selector,abiHash:b.abiHash,capabilityId:'stable:bytes',sourceRefs:[...b.sourceRefs],executionScope:null,executionScopeHash:null,authorityReview:{classification:'ordinary-direct',sourceRefs:[b.sourceRefs[0]],evidence:'review'}}]};expect(()=>prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow(/byte-bearing/);const good:any=fixture(snapshot(),['duplicate','duplicate']);expect(()=>validateUpdatePlan(good)).toThrow();});
  it('preserves exact v9 baseline and rejects pending deactivation application',()=>{const doc=snapshot(),p:any=basePlan(doc);const current=baseline.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions))[0];p.deactivations=[{capabilityId:current.capabilityId,expectedFullObjectSha256:fullCatalogFunctionSha256(current),reason:'operator proposal'}];const prepared=prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256);expect(prepared.deactivationProposals[0].status).toBe('proposed-inactive');expect(()=>assembleCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow(/deferred/);expect(prepared.previewCatalog.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions))).toHaveLength(675);});
  it('keeps unadmitted candidates out of build output and retains the full frozen baseline',()=>{const doc=snapshot(),built=assembleCatalogUpdate({chains:baseline.chains},basePlan(doc),[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256);expect(built.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions))).toHaveLength(673);expect(built.chains).toEqual(baseline.chains);});
  it('does not allow capability IDs to replace a baseline identity',()=>{const doc=snapshot(),old=baseline.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions))[0],p:any=fixture(doc,[old.capabilityId,'new:2']);expect(()=>prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow();});
  it('rejects relabeled baseline selector aliases, including scoped mandatory identities',()=>{const old=baseline.chains.flatMap(c=>c.contracts.flatMap(k=>k.functions)).find(f=>f.executionScope);expect(old).toBeDefined();const doc={schemaVersion:1,sources:[{sourceId:'official',url:'https://example.invalid/interface.json',retrievedAtUtc:'2026-10-05',evidence:'fixture'}],unresolved:[],families:[{familyId:'relabeled-family',familyVersion:'new-v1',chains:[{chainId:old!.chainId,status:'inactive',contracts:[{address:old!.contract,status:'inactive',functions:[{capabilityId:'candidate:alias',type:'contract_call',chainId:old!.chainId,contract:old!.contract,functionName:old!.functionName,signature:old!.signature,abi:old!.abi,status:'inactive',provenance:{sourceRef:'official',verifiedAt:'2026-10-05',status:'candidate'}}]}]}]}]};const binding=compileSourceSnapshotBindings(doc,updatePath)[0];const p:any={...basePlan(doc),admissions:[{sourcePath:updatePath,familyId:binding.familyId,familyVersion:binding.familyVersion,chainId:binding.chainId,contract:binding.contract,signature:binding.signature,selector:binding.selector,abiHash:binding.abiHash,capabilityId:'stable:relabeled-alias',sourceRefs:[...binding.sourceRefs],executionScope:null,executionScopeHash:null,authorityReview:{classification:'ordinary-direct',sourceRefs:[binding.sourceRefs[0]],evidence:'reviewed source alias'}}]};expect(()=>prepareCatalogUpdate({chains:baseline.chains},p,[{sourcePath:updatePath,document:doc}],baselinePin.rawSha256)).toThrow(/baseline selector/);});
});
