import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { isBareLegacyV9Check, loadCurrentCatalogUpdate, selectBareCatalogUpdateArgs } from '../../../../scripts/defi-catalog/update-cli-current';

const pointer='data/defi-catalog/updates/current.json';
const plan='data/defi-catalog/updates/test-batch/plan.json';
const hash=(data:string)=>createHash('sha256').update(data).digest('hex');
function fixture(){const root=mkdtempSync(resolve(tmpdir(),'catalog-current-'));mkdirSync(resolve(root,'data/defi-catalog/updates/test-batch'),{recursive:true});return root;}
function writePointer(root:string,planBytes='{}'){writeFileSync(resolve(root,plan),planBytes);writeFileSync(resolve(root,pointer),JSON.stringify({schemaVersion:1,planPath:plan,planRawSha256:hash(planBytes)}));}

describe('catalog current-plan pointer',()=>{
  it('falls back only when the pointer file is genuinely absent',()=>{const root=fixture();try{expect(loadCurrentCatalogUpdate(root)).toBeUndefined();expect(selectBareCatalogUpdateArgs(root,['generate'])).toEqual(['generate']);}finally{rmSync(root,{recursive:true,force:true});}});
  it('routes only a pointer-free bare check through legacy v9 module verification',()=>{expect(isBareLegacyV9Check(['check'])).toBe(true);expect(isBareLegacyV9Check(['check','--input','data/defi-catalog/v9/catalog.json'])).toBe(false);expect(isBareLegacyV9Check(['check','--plan','data/defi-catalog/updates/test-batch/plan.json'])).toBe(false);expect(isBareLegacyV9Check(['generate'])).toBe(false);const root=fixture();try{expect(selectBareCatalogUpdateArgs(root,['check'])).toEqual(['check']);writePointer(root);expect(selectBareCatalogUpdateArgs(root,['check'])).toEqual(['check','--plan',plan]);}finally{rmSync(root,{recursive:true,force:true});}});
  it('selects a valid raw-byte-pinned plan only for bare generate/check/diff',()=>{const root=fixture();try{writePointer(root,' {"schemaVersion":1}\n');expect(loadCurrentCatalogUpdate(root)).toBe(plan);for(const mode of ['generate','check','diff'])expect(selectBareCatalogUpdateArgs(root,[mode])).toEqual([mode,'--plan',plan]);expect(selectBareCatalogUpdateArgs(root,['generate','--input','data/defi-catalog/v9/catalog.json'])).toEqual(['generate','--input','data/defi-catalog/v9/catalog.json']);expect(selectBareCatalogUpdateArgs(root,['generate','--plan',plan])).toEqual(['generate','--plan',plan]);}finally{rmSync(root,{recursive:true,force:true});}});
  it('rejects malformed schemas, traversal paths, and raw plan byte changes',()=>{const root=fixture();try{writePointer(root);const path=resolve(root,pointer);writeFileSync(path,JSON.stringify({schemaVersion:1,planPath:plan,planRawSha256:hash('{}'),extra:true}));expect(()=>loadCurrentCatalogUpdate(root)).toThrow();writeFileSync(path,JSON.stringify({schemaVersion:1,planPath:'data/defi-catalog/updates/../plan.json',planRawSha256:hash('{}')}));expect(()=>loadCurrentCatalogUpdate(root)).toThrow();writePointer(root,'{}');writeFileSync(resolve(root,plan),'{} ');expect(()=>loadCurrentCatalogUpdate(root)).toThrow(/digest mismatch/);}finally{rmSync(root,{recursive:true,force:true});}});
  it('fails closed on pointer, parent, plan, and broken symlinks',()=>{const root=fixture();try{writePointer(root);const pointerPath=resolve(root,pointer);rmSync(pointerPath);symlinkSync(resolve(root,'missing-target'),pointerPath);expect(()=>loadCurrentCatalogUpdate(root)).toThrow(/symbolic link/);rmSync(pointerPath);const updates=resolve(root,'data/defi-catalog/updates'),real=resolve(root,'real-updates');mkdirSync(real);rmSync(resolve(root,'data/defi-catalog/updates'),{recursive:true});symlinkSync(real,updates);expect(()=>loadCurrentCatalogUpdate(root)).toThrow(/symbolic link/);}finally{rmSync(root,{recursive:true,force:true});}});
  it('rejects plan-file symlinks and an incorrect pointer digest',()=>{const root=fixture();try{writePointer(root);const planPath=resolve(root,plan),original=resolve(root,'target.json');writeFileSync(original,'{}');rmSync(planPath);symlinkSync(original,planPath);expect(()=>loadCurrentCatalogUpdate(root)).toThrow(/symbolic link/);rmSync(planPath);writeFileSync(planPath,'{}');writeFileSync(resolve(root,pointer),JSON.stringify({schemaVersion:1,planPath:plan,planRawSha256:'0'.repeat(64)}));expect(()=>loadCurrentCatalogUpdate(root)).toThrow(/digest mismatch/);}finally{rmSync(root,{recursive:true,force:true});}});
});
