import { buildInvoicePdf, escapePdfText, type InvoicePdfDocument } from './invoice-pdf.writer';

function sampleDocument(): InvoicePdfDocument {
  return {
    title: 'SOFA ONE Invoice',
    invoiceNumber: 'inv-1',
    period: '2026-05',
    issuedAt: '2026-06-02',
    status: 'paid',
    currency: 'USD',
    amount: '84',
    lines: [
      { description: 'Monthly fee — Starter', amount: '49' },
      { description: 'Outbound volume tier 1', amount: '35' },
    ],
    footer: 'Generated by SOFA ONE. Not a tax receipt.',
  };
}

describe('escapePdfText', () => {
  it('keeps plain printable ASCII unchanged', () => {
    expect(escapePdfText('SOFA ONE Invoice 2026-05')).toBe('SOFA ONE Invoice 2026-05');
  });

  it('replaces non-ASCII characters so only ASCII reaches the PDF', () => {
    expect(escapePdfText('Monthly fee — 价格 100%')).toBe('Monthly fee ? ?? 100%');
  });

  it('escapes PDF text-string delimiters', () => {
    expect(escapePdfText('a(b)\\c')).toBe('a\\(b\\)\\\\c');
  });

  it('collapses line breaks into a single space', () => {
    expect(escapePdfText('line1\nline2\r\nline3')).toBe('line1 line2 line3');
  });
});

describe('buildInvoicePdf', () => {
  it('produces a structurally valid minimal PDF', () => {
    const pdf = buildInvoicePdf(sampleDocument());
    const text = pdf.toString('ascii');

    expect(Buffer.isBuffer(pdf)).toBe(true);
    expect(text.startsWith('%PDF-1.4')).toBe(true);
    expect(text.trimEnd().endsWith('%%EOF')).toBe(true);
    expect(text).toContain('/Type /Catalog');
    expect(text).toContain('/BaseFont /Helvetica');
    expect(text).toContain('/BaseFont /Helvetica-Bold');
    expect(text).toContain('xref');
    expect(text).toContain('/Root 1 0 R');
  });

  it('writes correct xref offsets so a PDF reader can resolve objects', () => {
    const text = buildInvoicePdf(sampleDocument()).toString('ascii');
    const startxrefMarker = text.lastIndexOf('startxref');
    const xrefOffset = Number(
      text.slice(startxrefMarker + 'startxref'.length).trim().split('\n')[0],
    );
    expect(text.indexOf('xref\n')).toBe(xrefOffset);
    expect(Number.isInteger(xrefOffset)).toBe(true);
  });

  it('embeds the invoice facts as escaped ASCII text', () => {
    const text = buildInvoicePdf(sampleDocument()).toString('ascii');
    expect(text).toContain('(SOFA ONE Invoice)');
    expect(text).toContain('(Invoice: inv-1)');
    expect(text).toContain('(Period: 2026-05)');
    expect(text).toContain('(Amount: 84 USD)');
    expect(text).toContain('(Monthly fee ? Starter)');
  });

  it('positions text with a full six-operand text matrix so readers extract it', () => {
    const text = buildInvoicePdf(sampleDocument()).toString('ascii');
    // `Tm` requires 6 operands (a b c d e f); a 2-operand Tm is a syntax error
    // that makes pdftotext and other readers drop the text layer.
    expect(text).toContain('1 0 0 1 72 720 Tm');
    expect(text).not.toMatch(/^\d+ \d+ Tm$/m);
  });

  it('never emits raw non-ASCII bytes into the content stream', () => {
    const doc = sampleDocument();
    doc.lines = [{ description: '价格 ￥200 中文', amount: '200' }];
    const text = buildInvoicePdf(doc).toString('ascii');
    // Every content-stream byte must be printable ASCII.
    for (const char of text) {
      expect(char.charCodeAt(0)).toBeLessThanOrEqual(0x7e);
    }
  });

  it('rejects documents with more lines than fit on a single page', () => {
    const doc = sampleDocument();
    doc.lines = Array.from({ length: 101 }, (_, i) => ({ description: `line ${i}`, amount: '1' }));
    expect(() => buildInvoicePdf(doc)).toThrow(RangeError);
  });
});
